import Head from "next/head";
import Navbar from "../components/nav/Navbar";
import Main from "../components/Main";
import About from "../components/About";
import Projects from "../components/projects/Projects";
import Skills from "../components/Skills";
import Contact from "../components/contact/Contact";
import { useTranslation } from "next-i18next";
import { useRouter } from "next/router";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useEffect, useRef } from "react";
import Link from "next/link";
import navStyle from "../utils/navStyle";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}

export default function Home({ locale }) {
  const { t } = useTranslation();

  const router = useRouter();
  console.log(router);

  useEffect(() => {
    navStyle();
  });

  return (
    <div>
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="ml-10 md:ml-32 text-slate-200 scroll-smooth">
        {/* <h1>{t("common:title")}</h1>
        <h1>{locale}</h1> */}

        {/* {mainInview && window.history.replaceState(null, null, "#main")} */}
        <Main />

        {/* {projectInview && window.history.replaceState(null, null, "#projects")} */}
        <Projects />

        {/* {skillsInView && window.history.replaceState(null, null, "#skills")} */}
        <Skills />

        {/* {aboutInview && window.history.replaceState(null, null, "#about")} */}
        <About />

        {/* {contactInView && pushContact} */}
        <Contact />
      </div>
    </div>
  );
}
